fix: gas estimation
The function `estimateGas` from a `PublicClient` requires a `account`
field to be used when making calls to an ERC20 contract, otherwise
the following error is raised:

```
EstimateGasExecutionError: Execution reverted with reason: ERC20: transfer from the zero address
```

This commit fixes this issue by always passing the `account` parameter as
the `from` in the transaction, as that will be the address interacting
with the ERC20 contract